apiVersion: v1
kind: ConfigMap
data:
  USERS_TODO_TABLE: ___INSERT_AWS_USERS_TODO_TABLE___
  USERID_INDEX: ___INSERT_AWS_USERID_INDEX___
  TODOS_S3_BUCKET: ___INSERT_AWS_TODOS_S3_BUCKET___
  THUMBNAILS_S3_BUCKET: ___INSERT_AWS_THUMBNAILS_S3_BUCKET___
  SIGNED_URL_EXPIRATION: "300"
  AWS_REGION: ___INSERT_AWS_REGION___
  AWS_PROFILE: ___INSERT_AWS_PROFILE___
  TODO_VERSION: v0
  URL: http://localhost:3000  
metadata:
  name: env-config